name: CI/CD Backend Deploy

on:
  push:
    branches:
      - main  # trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/lms-backend-demo:demo .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/lms-backend-demo:demo

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # pull latest docker image
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/lms-backend-demo:demo
          
          # stop old container if running
          if [ $(sudo docker ps -q -f name=lms-backend) ]; then
            sudo docker stop lms-backend
            sudo docker rm lms-backend
          fi
    
          # run new container
          sudo docker run -d \
              --name lms-backend \
              --restart unless-stopped \
              -p 80:3000 \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e RDS_ENDPOINT="${{ secrets.RDS_ENDPOINT }}" \
              -e DB_NAME="${{ secrets.DB_NAME }}" \
              ${{ secrets.DOCKER_USERNAME }}/lms-backend-demo:demo
